version: '3'
name: bot_junior_python_developer_task
services:
  nats:
    image: nats:latest
    entrypoint: /nats-server -js
    ports:
      - "4222:4222"
    volumes:
      - ./nats/data:/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/root/redis

  bot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      nats:
        condition: service_started
      redis:
        condition: service_started
    command:
      python -m bot